### ISSUE TITLE
Syntax highlighting

### ISSUE THREAD

**Issue by simurai** [montagejs/montagejs.org#11]
Something that is still missing in the Docs is syntax highlighting. Currently it's kinda hard to read the code samples. It's just blue.

![sh](https://f.cloud.github.com/assets/378023/187489/8a63b26c-7d5f-11e2-8503-356a87d8a123.png)

Has somebody suggestions on which library to use?

**Comment by Stuk** [comment]
We should be able to just use a pygments style sheet, as all the html classes are there.

Do you want to pick your favourite from here: https://github.com/richleland/pygments-css and add it?

**Comment by Stuk** [comment]
Previews here: http://igniteflow.com/pygments/themes/ Edit: all the ones that look terrible should have a dark background. For example, Monokai looks like this: http://www.monokai.nl/blog/wp-content/asdev/monokaiTheme.gif

**Comment by simurai** [comment]
Ohh.. great.. thanks. I kinda like this: http://igniteflow.com/pygments/manni/ But hard to say when not in use.

Dark looks pretty cool, but I think when just used in smaller areas (code blocks) it's harder to read. Ok, I'll try to add a light one and maybe a subtle background.

**Comment by mczepiel** [comment]
Literally paiting the bikeshed here but I'm a fan of the [solarized project](http://ethanschoonover.com/solarized)

Somebody has a [light solarized pygment](https://github.com/john2x/solarized-pygment)

**Comment by simurai** [comment]
A fan too.. use a variation in my editor.

**Comment by francoisfrisch** [comment]
yes , really like the solarized color scheme, first one I really get attached to.

**Comment by simurai** [comment]
Ok.. added Solarized, but brightened the background a bit.

![solarized](https://f.cloud.github.com/assets/378023/188763/9a3f54da-7e0d-11e2-8d7c-3a5748e6930c.png)

And when you select something (the "install" in the screenshot), it's the more darker yellow. Enough contrast? It's already live: http://montagejs.org/docs/Quick-Start.html

**Comment by Stuk** [comment]
I think more contrast would be better. I imagine people are going to be copy and pasting from the docs a lot, so the selection should be really clear.

**Comment by marchant** [comment]
I agree, more contrast!

**Comment by simurai** [comment]
OK.. how about dark with white text:

![sh](https://f.cloud.github.com/assets/378023/192858/660c1dac-7f6f-11e2-9c58-d4c2693c39e7.png)

**Comment by Stuk** [comment]
Much better!
