### ISSUE TITLE
quickstart instructions should just be on the index page

### ISSUE THREAD

**Issue by mczepiel** [montagejs/montagejs.org#12]
The bare minimum for getting started should be on the main page so people can figure out how to get started without even having to follow a link.

There are too many calls to action there right now, it confusing, and even clicking one of them is a big commitment.

**Comment by angelxmoreno** [comment]
Where exactly is the quick start instructions in the repo? I expected them to be in "montagejs.org/source/docs/" but I do not see them there.

**Comment by simurai** [comment]
Hi. Currently (as of August 1st) things are a bit in flux. The "quick start" instructions are now a "Getting Started" guide and the source is in the [jekyll branch](https://github.com/montagejs/montagejs.org/blob/jekyll/docs/getting-started.md). But you can also check it out on the [montagejs.org](http://montagejs.org/docs/quick-start.html) site with nicer formatting.

**Comment by simurai** [comment]
Ok, "Getting Started" guide is now:

Live: http://montagejs.org/docs/getting-started.html
Source: https://github.com/montagejs/montagejs.org/blob/gh-pages/docs/getting-started.md
