### ISSUE TITLE
"html5 framework" text should not be blue like a link

### ISSUE THREAD

**Issue by mczepiel** [montagejs/montagejs.org#13]
I keep wanting to click on it, but that might just be me. I understand it matches the logo color.

**Comment by simurai** [comment]
Hmm.. another color feels a bit off.. how about just a lighter gray?

![hl](https://f.cloud.github.com/assets/378023/193325/616e9c40-7f81-11e2-993f-4a5d64d044ff.png)

**Comment by simurai** [comment]
Also, highlighting the words "Web Apps"?

An **HTML5 framework** for building modern **Web Apps**.
