### ISSUE TITLE
Nit: wrong indentation

### ISSUE THREAD

**Issue by NV** [montagejs/montagejs.org#18]
http://montagejs.org/docs/quick-start.html#Assign-Value-Through-Bindings
Indentation for `name` is wrong:

``` javascript
exports.NameTag = Component.specialize(/** @lends NameTag# */ {
    constructor: {
        value: function NameTag() {
            this.super();
        }
    },
        name: {
            value: "Alice"
        }
});
```

**Comment by francoisfrisch** [comment]
Fixed with montagejs/montage.wiki#da26a20

**Comment by NV** [comment]
Oh, I didn’t realize it’s available on https://github.com/montagejs/montage/wiki/Quick-Start

**Comment by francoisfrisch** [comment]
it gets copied over
