### ISSUE TITLE
Social media buttons

### ISSUE THREAD

**Issue by eliseosoto** [montagejs/montagejs.org#3]
At least Twitter and Google+ buttons.

Or even it'd be cool to have the Unofficial Github buttons http://ghbtns.com/

**Comment by simurai** [comment]
Yep, good point. In our case, Github buttons would be great.

**Comment by simurai** [comment]
Added: http://montagejs.org/#social (bottom). But Twitter and G+ don't load. ;-( Maybe it can't be in a .reel? Gonna try to add it straight to the index.

**Comment by simurai** [comment]
Ok, moving it to `index.html` seemed to work. Maybe Montage needs a "social button" component.

Thanks, @eliseosoto
