### ISSUE TITLE
Improve 404 redirects

### ISSUE THREAD

**Issue by simurai** [montagejs/montagejs.org#34]
### Problem

Currently if we rename a file in the docs (or anywhere else), we add a physical `html` file with a meta refresh to the new one. [Example](https://github.com/montagejs/montagejs.org/blob/gh-pages/docs/kitchen-sink.html) 
### Solution

Would it be possible to redirect these only in the [/404.html](https://github.com/montagejs/montagejs.org/blob/gh-pages/404.html) script? Basically we manually just add an array with all the redirects and then the script checks the url and if there is a matching one, it goes to that page?

``` js
var redirects = [
    [ '/docs/Quick-Start.html', '/docs/montagejs-setup.html' ],
    [ '/docs/Component-draw-cycle.html', '/docs/draw-cycle.html' ]
    // etc..
];
```
### Benefits

That would make things much easier.
- We would have a nice overview of everything
- quicker to edit -> just add a line instead of fiddling with html files.
- we could remove all the physical html files that clutter up everywhere and things stay clean (this point is actually my biggest )
- allows having different case sensitive redirects, like `Quick-Start.html` and `quick-start.html`.

**Comment by asolove** [comment]
This might be a good thing to check out: https://github.com/tsmango/jekyll_alias_generator

**Comment by simurai** [comment]
Would that work for any kind of page? In the description it only mentions "for posts".

**Comment by asolove** [comment]
Maybe not. I mostly meant we could look at the implementation (https://github.com/tsmango/jekyll_alias_generator/blob/master/_plugins/alias_generator.rb) to get some ideas.

**Comment by Stuk** [comment]
Github pages [doesn't allow plugins to run](https://help.github.com/articles/pages-don-t-build-unable-to-run-jekyll#unsafe-plugins) so we would have to go back to building locally. Although it is past the time when we should just run our own server...
