### ISSUE TITLE
Broken link from minit template link

### ISSUE THREAD

**Issue by 3on** [montagejs/montagejs.org#62]
This commit removed that link, but we should anyhow redirect to where ever it should.
I've made sure I've updated minit to the latest version on NPM (https://npmjs.org/package/minit) and I get that welcome.reel with this broken link
http://montagejs.org/docs/quick-start.html

https://github.com/montagejs/minit/blob/26771ca54d89bd81e43586234c815b0aa23fe1e5/templates/app/__name__/ui/welcome.reel/welcome.html#L31

**Comment by simurai** [comment]
There is already a redirect for `Quick-Start.html` (upper case): https://github.com/montagejs/montagejs.org/blob/gh-pages/docs/Quick-Start.html

I think it's not possible to have upper and lower case at the same time, right? At least not on OS X. It complains the file already exists.

Maybe it's a good time to look into #34 again? :innocent:

**Comment by mikokim** [comment]
There will be a new version of minit, which installs a new project template (sans welcome.reel).

**Comment by Stuk** [comment]
Fixed by above PR and new setup guide.
