### ISSUE TITLE
Write a post on types

### ISSUE THREAD

**Issue by kriskowal** [montagejs/montagejs.org#8]
I talked to @romancortes today about types.

The issue in question was how to subclass, override a property, and add integrity checks to inheritance. The solution is similar to Python’s metaclasses.

``` javascript
var Polyline = Montage.create(Montage, {
    create: {
        value: function (Parent, properties) {
            var heir = Parent.create(Parent, properties);
            if (!(heir.bezierType instanceof this.bezierType)) {
                throw new TypeError("Heirs must have a compatible bezierType");
            }
            return heir;
        }
    },
    bezierType: {
        value: Bezier
    }
});

var CubicPolyline = Polyline.create(Polyline, {
    bezierType: {
        value: CubicBezier
    }
});
```

Noting of course the redundancy of `Type.create(Type, properties)` and that in overriding `create`, you have to take care of both the initialization and inheritance usage. Ideally you could override each with independent methods.

This led to a discussion of how to set up a base type such that as many routines as possible can be shared by heirs, while simultaneously leaving open opportunities to specialize some methods for specific performance optimizations.  For example, how to generalize an any-dimensional matrix but still allow a 3x3 matrix type to use a flat array as its internal storage.  I cite `splice` and `reduce` as great targets for funneling lots of method definitions through a common implementation in `collections`.

This also led to a discussion of problems and benefits of the JavaScript Constructor/Prototype pattern, and which of these problems the Montage type system addresses.  Some notes:
1. a type declaration is not a self-contained indented block
2. a constructor cannot be passed around as a factory function.  it must be called with `new`, unless special arrangements are made either inside the constructor or with closures.
3. to specify an alternate parent prototype, you have to overwrite the constructor.prototype. in so doing, you lose the prototype.constructor property and have to make special arrangements to get it back.  this is a shame because `this.constructor` is handy for cloning and type checking.
4. the popular pattern for overwriting the prototype is to set it to an _instance_ of the parent type. This works sometimes, but breaks in esoteric cases with shared state. Object.create solves this problem, if you know about it.
5. the constructor and initializer are coupled, so if you create a new type, you _must_ define its constructor, even if only to call the parent type’s constructor.

All this amounts to about this much boilerplate to get the best practices:

``` javascript
function Type(/* ...arguments */) {
    if (!(this instanceof Type)) {
        return Type.apply(Object.create(Type.prototype), arguments);
        // or just new Type with a copy of the argument list
    }
    Parent.call(this); // with any arguments relevant to the ancestors
    // initialization
}

Type.prototype = Object.create(Parent.prototype);

Type.prototype.constructor = Type;

// method declarations...
```

Of course the advantage of using the Constructor/Prototype patterns is that the V8 compiler pays close attention to `this` property assignment to generate hidden classes in constructor functions.

Montage’s inheritance and instantiation patterns solve the issue of shared initializers and a succinct definition block.  Tracking the type’s own constructor becomes moot, however differentiating instantiation from inheritance is problematic, lending to awkwardness in the metaclass pattern.  Montage also handles alternate initializer argument patterns well, but Montage does not provide a factory method.

These are all good topics for tutorials.

**Comment by Stuk** [comment]
@kriskowal still needed? Something for @segphault?

**Comment by kriskowal** [comment]
All the facts above have changed. The proposed changes have occurred. We still need tutorials for the use of `specialize` and `super`, and slightly later, tutorials on **overriding** `specialize` and `defineProperty` with the various motivating use cases.

**Comment by Stuk** [comment]
k, closing this issue. Want to create more in jira?
