### ISSUE TITLE
Use GitHub's CDN

### ISSUE THREAD

**Issue by simurai** [montagejs/montagejs.org#93]
Github added a CDN feature: https://github.com/blog/1715-faster-more-awesome-github-pages

After reading that post, I think we would need to do the following:
1. Rename the `montagejs.org` repo to `montagejs.github.io` so it becomes a "user page" and not a "project page". **Update**: Not needed.
2. At our domain provider change from an `A` record to an `ALIAS` (if they support it).

Is that correct?

**Comment by Stuk** [comment]
We don't need to rename the repo.

We do either need to use an `ALIAS` record, or switch to using www.montagejs.org instead of the plain montagejs.org

**Comment by simurai** [comment]
Ahh.. ok. Hopefully `ALIAS` works.. don't really like the `www`. I think we're using http://www.gandi.net. Who has access? @PierreFrisch?

**Comment by Stuk** [comment]
yep, and @francoisfrisch

**Comment by PierreFrisch** [comment]
Please Close and file in JIRA

**Comment by francoisfrisch** [comment]
problem solved
